name: Run Azure Login with OpenID Connect and PowerShell
on: [workflow_dispatch]

permissions:
      id-token: write
      contents: read
      
jobs: 
  Windows-latest:
      runs-on: ubuntu-latest
      steps:
        - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
            enable-AzPSSession: true

        - name: 'Get resource group with PowerShell action'
          uses: azure/powershell@v1
          with:
             inlineScript: |
               Get-AzResourceGroup
             azPSVersion: "latest"

        - name: Create annotation for build error
          run: echo "::error::Set the Octocat variable"
        - name: Create annotation for build error
          run: echo "::warning::Set the Octocat variable"
        - name: Create annotation for build error
          run: echo "::debug::Set the Octocat variable"
        - name: Create annotation for build error
          run: echo "::notice::Set the Octocat variable"
        - name: Create annotation for build error
          run: exit 1
             

